### ISSUE TITLE
Add more teaching links

### ISSUE THREAD

**Issue by tpetricek** [fsharp/fsfoundation#147]
* http://cs.ttu.ee/courses/itt8060/ (Tallinn)
 * http://www2.imm.dtu.dk/courses/02157/ (DTU)
 * http://www.kurser.dtu.dk/02257.aspx?menulanguage=en-gb (DTU)

**Comment by dsyme** [comment]
I'll close this. One of the links are dead but the other two courses could be mentioned.

@tpetricek can you send a PR if you'd like to update this material?
