### ISSUE TITLE
Create up-for-grabs page 

### ISSUE THREAD

**Issue by forki** [fsharp/fsfoundation#150]
Look at http://up-for-grabs.net/#/ - it's a very interesting concept. 

We should have a page where we mirror the listed F# projects.

**Comment by dsyme** [comment]
@forki  - I think it would be great to have this. Probably not on fsharp.org itself but we could add a link under "Contribute".

**Comment by dsyme** [comment]
I'll close this as an fsharp.org issue but please do submit a PR to add to "Contribute" if there is an appropriate resource to link to?
