### ISSUE TITLE
Be clear about what version of F# we recommend (3.0 vs 3.1)

### ISSUE THREAD

**Issue by rneatherway** [fsharp/fsfoundation#192]
See http://fsharp.org/use/linux/ option 2 which talks about building 3.0 but doesn't include a git checkout for the 3.0 branch. I'm not sure how solid 3.1/master is currently so I'm sure whether to update it to say 3.1 or to switch to 3.0.

**Comment by dsyme** [comment]
This has already been fixed to say F# 3.1
