### ISSUE TITLE
Add list of proposed student projects to fsharp.org

### ISSUE THREAD

**Issue by ghost** [fsharp/fsfoundation#206]
Matt Parkinson and Jon Harrop are planning on adding a list of possible student projects to fsharp.org, as ideas for people teaching with F#, and this is a placeholder item to get together an initial list of ideas for that.

**Comment by dsyme** [comment]
A list along these lines is now curated at  https://github.com/c4fsharp/c4fsharp.github.io/blob/master/project-ideas.md
