### ISSUE TITLE
Information for F# trainers

### ISSUE THREAD

**Issue by jdh30** [fsharp/fsfoundation#212]
I gave another one week course to one of the world's largest insurance companies last month and found myself unable to demo any Nuget packages because I didn't have an internet connection. In fact, I often don't have an internet connection and want to use packages. Nuget does not support this out-of-the-box but apparently there are hacks to make a local repository: http://www.hanselman.com/blog/HowToAccessNuGetWhenNuGetorgIsDownOrYoureOnAPlane.aspx

This made me think: we should devote part of fsharp.org to information like this for F# trainers. Maybe we could also have links to videos/slideshows of F# talks?

What do you think?

**Comment by dsyme** [comment]
I'll close this issue out as it's more than a year old.
