### ISSUE TITLE
installation instructions (mono from git source) on web page do not work 

### ISSUE THREAD

**Issue by jwaldmann** [fsharp/fsfoundation#216]
http://fsharp.org/use/linux/ says Option 2: 1. .. or 'git clone https://github.com/mono/mono' but the build there breaks with 

```
MCS     [net_2_0] Microsoft.Build.Engine.dll
Microsoft.Build.BuildEngine/Engine.cs(114,81): error CS0117: `Microsoft.Build.Utilities.TargetDotNetFrameworkVersion' does not contain a definition for `Version30'
/tmp/mono/mcs/class/Microsoft.Build.Engine/./../../class/lib/net_2_0/Microsoft.Build.Utilities.dll (Location of the symbol related to previous error)
Microsoft.Build.BuildEngine/Engine.cs(116,81): error CS0117: `Microsoft.Build.Utilities.TargetDotNetFrameworkVersion' does not contain a definition for `Version35'
/tmp/mono/mcs/class/Microsoft.Build.Engine/./../../class/lib/net_2_0/Microsoft.Build.Utilities.dll (Location of the symbol related to previous error)
Compilation failed: 2 error(s), 0 warnings
```
I can force the build with `--with-profile2=no --with-profil3=no --with-profile4=yes` but then I get a version of `mono` that cannot build `fsharp` (profile2 would be needed?)

Building mono from the latest source tarball release http://download.mono-project.com/sources/mono/mono-3.4.0.tar.bz2 , and then fsharp with that, is working fine.

(all of this on ubuntu precise x86_64 GNU/Linux 3.8.0-30)

**Comment by dsyme** [comment]
This is old and we haven't had a report of it for a long time. I'm closing it, please reopen if we get confirmation that the current instructions don't work.
