### ISSUE TITLE
F# package not actually available in Debian testing

### ISSUE THREAD

**Issue by kiwidrew** [fsharp/fsfoundation#219]
The "Use F# on Linux" page (http://fsharp.org/use/linux/) falsely claims that the F# package is available in Debian testing.  It is not.  According to Debian QA, there is a bug which prevents the package from installing;  and so the package will not be added to testing until this bug is addressed:

https://release.debian.org/migration/testing.pl?package=fsharp

Please update the documentation to reflect the current reality.

**Comment by dsyme** [comment]
Looks like this has been fixed
