### ISSUE TITLE
Component Design Guidelines don't specify naming conventions of modules

### ISSUE THREAD

**Issue by svick** [fsharp/fsfoundation#274]
In §3.1, the guidelines specify that all "Concrete types" should PascalCase. I believe this should include modules, but then the note lists which kinds of types are meant, and doesn't mention modules:

> Concrete types are structs, classes, enumerations, delegates, records, and unions. Though type names are traditionally lowercase in OCaml, F# has adopted the .NET naming scheme for types.

I think modules should be added to the list in the note.

(I would make a pull request for this, but I don't have Word installed.)

**Comment by dsyme** [comment]
Closing out this old issue

The component guidelines are now here: https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines 

Please make the edit there directly
