### ISSUE TITLE
Issues with new home page

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsfoundation#332]
This rolling issue is to discuss the new home page by @TahaHachana, from #317 . Please add comments below. Issues I've seen so far:

* It feels like the Rajdhani font is not appropriate for headings and main-body text. It's fine for the front page and the navbar, but not for things like the guides or testimonials. 

* On http://fsharp.org/testimonials/, the word "Testimonials" is overlaid by the five-item social-sharing toolbar that flies in from the left.

* The code samples that were on the front page didn't feel quite right.

* The "fly-in" effect of the social-sharing navbar is a little distracting

* Training --> "Online Learning" doesn't seem to go to the right anchor because of the navbar problem

* Training --> "Video Lectures" doesn't seem to go to the right anchor because of the navbar problem

* Training --> "Textbooks for F#" doesn't seem to go to the right anchor because of the navbar problem

* When you press "Install" on the front page the dropdown shows below, partly off-screen.

* On smaller screen sizes, when using the minimized toolbar with the three stripes, the second-level of toolbar choices shows in grey font

**Comment by ReedCopsey** [comment]
@tpetricek I had to make other changes to the sponsor list for legal reasons - I got rid of the shaded backgrounds while I was at it.
