### ISSUE TITLE
Video assets

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsfoundation#342]
A thought occurred to me while looking at the shiny new fsharp.org….

It feels like we are under-utilizing our collected [video assets](http://fsharp.org/videos) (this an incomplete collection but a good one - there are more recent videos that have come online since @TahaHachana pulled that collection together). 

Do you have any thoughts on how we might change this, to get the right people watching the right videos more often?

Here are some initial thoughts
-   Not all videos are appropriate for all audiences, so we can’t put rotating videos on the front page of fsharp.org.  
-   Perhaps we should be using the videos more proactively in the guides on fsharp.org?  There's one example of this in the ["apps-and-games" section](https://github.com/fsharp/fsfoundation/tree/gh-pages/guides/apps-and-games).  But it's not done that well and it feels like we could do better.
-   Perhaps the videos should be on [Community for F#](http://csfsharp.net)?

This occurred to me in the context of videos assets that Microsoft have produced over time, like the B-Movie Madness video by Donna Malayeri (which I can’t locate but which I’m sure I could find again), the “Don at the Coffee Machine” video and new video done by @latkin coming out in the next month.  I’d like to think how we can make the most from these assets and get the right people watching them.

**Comment by StachuK1992** [comment]
Poke. How can I help?

**Comment by jwood803** [comment]
I actually forgot about this. :[

**Comment by StachuK1992** [comment]
Things happen! How can I help?

**Comment by StachuK1992** [comment]
Unless anyone has issues with it, I will take this over.
I have some ideas that I want to explore. Expect some PR within a week or so.

**Comment by jwood803** [comment]
Feel free to jump on it! :]

Look forward to the PR and reach out here if you need any help.

**Comment by dsyme** [comment]
@jwood803 - did you get to make progress on this?  Otherwise we should probably just close the issue,

**Comment by jwood803** [comment]
Sorry, I didn't. I thought @StachuK1992 was taking over, but perhaps we can revisit this if it's still needed?

**Comment by dsyme** [comment]
Well, better curation/update/search/... of the video assets is certainly still needed - either on c4fsharp.net or here on fsharp.org or even via some other service more suitable for this.  A lot of people go to http://fsharp.org/videos/1 and I presume they kind of get lost amongst the content there, which is also getting a little old now.

**Comment by jwood803** [comment]
True, the latest one is, if it's the most recent one, is about nine months old :}

**Comment by ptrelford** [comment]
Yet more F# related video assets are listed on Lanyrd: http://lanyrd.com/topics/f/video/

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by beginningfsharp** [comment]
Also, all the references to Pluralsight videos have disappeared. I'm sure there were links to my own and Mark Seemann's at one point; and there should also be links to Dave Fancher's and Tomas's courses.

**Comment by beginningfsharp** [comment]
OK, unless anyone objects I'm going to take this on (as I stand to gain by re-including my own courses!).

Outline plan:
1) Generate a database of the existing content, including slots for the tags suggested above
2) Clean the list (make sure links not dead etc)
3) Populate the tags (manual)
4) Add any missing courses (including several from PluralSight - other suggestions welcome)
5) Regenerate something approximating the existing markdown pages but with the cleaned content and showing the tags.

--- At this point we have a cleaner more up to date list but no ability so search/drill down by tag.

6) Work out how to provide a tag-searchable page.

I'll maintain a separate github repo of any code I use to create the database and regenerate the markdown pages.

**Comment by misterspeedy** [comment]
Very sketchy code for step 1) here: https://github.com/misterspeedy/FSharpOrgVideoCuration

Don't judge me.

**Comment by misterspeedy** [comment]
OK, here's a google sheet with the existing database, pulled from fsharp.org:

https://docs.google.com/spreadsheets/d/1aQCq1SOtBdB6Kqnq6Aup_szCvi0QEdxr3t__VhEwNHY/edit?usp=sharing

It would be great if we could crowdsource categorising and tagging these (i.e. filling in columns G-K).

If you'd like to join in mail me (kit dot eason at gmail dot com) and I'll send you an editable link.

**Comment by jwood803** [comment]
I know this is a bit old, but would Azure's [Video Indexer](https://azure.microsoft.com/en-us/services/cognitive-services/video-indexer/) help with this?

**Comment by dsyme** [comment]
Closing this old discussion
