### ISSUE TITLE
Navbar look issue on iPad

### ISSUE THREAD

**Issue by TahaHachana** [fsharp/fsfoundation#390]
On iPads the navbar dropdown menus show up as in the attached screenshot. This might not be iPad specific. The navbar also wraps into 2 rows and doesn't look good. The problem was reported by @vasily-kirichenko.
![fsharporgipad](https://cloud.githubusercontent.com/assets/1418447/5602367/8ded702a-9348-11e4-9d62-0f1348009b1c.jpg)

**Comment by TahaHachana** [comment]
There are three solutions here:
* Reduce the amount of navbar items
* Hide an item
* Customize Bootstrap
I went with solution 2 since removing an item isn't an option here and customizing Bootstrap might impact other parts of the website and would mean serving a local file not a CDN hosted one.

**Comment by ReedCopsey** [comment]
Will this "fix" also remove the entire menu on mobile platforms (where it works fine now) as well?  I think this is a reasonable compromise for a short term solution, but it would be good to try to find a better permanent fix which didn't leave the content different on different platforms.

**Comment by TahaHachana** [comment]
The "Contribute" item would be hidden only on tablets (≥768px), if the issue persists after migrating to Bootstrap 4 (which is going to feature a brand new navbar) then we'll customize it.

**Comment by dsyme** [comment]
Do you mean "<= 768px"? Just wondering why it would only apply to bigger tablets. Thanks

**Comment by TahaHachana** [comment]
[≥768px actually](http://getbootstrap.com/css/#responsive-utilities-classes), I found a better solution (IMHO) which consists in reducing the right and left padding of the navbar items by 2px. This how the navbar would look on an iPad 3 or 4:
![fsorgnavbarfix](https://cloud.githubusercontent.com/assets/1418447/5609328/114d9eee-949e-11e4-8968-c3797631eafa.PNG)

**Comment by ReedCopsey** [comment]
I'd prefer this option, as it wouldn't change the content when viewed on an iPad.

**Comment by vasily-kirichenko** [comment]
Looks good.
