### ISSUE TITLE
http://fsharp.org/use/linux/ should mention PKG_CONFIG_PATH for Option 2: Build and install the F# 3.1 runtime, compiler and tools

### ISSUE THREAD

**Issue by davidpodhola** [fsharp/fsfoundation#405]
Following http://fsharp.org/use/linux/ Option 2: Build and install the F# 3.1 runtime, compiler and tools on Centos 6.6 I felt into https://github.com/fsharp/fsharp/issues/313. Maybe https://github.com/fsharp/fsharp/issues/313#issuecomment-56312155 should be mentioned.

Thanks for the great website!

**Comment by dsyme** [comment]
Hi @davidpodhola , Cool. Could you send a pull request to adjust the documentation? Edit directly in the browser [here](https://github.com/fsharp/fsfoundation/blob/gh-pages/use/linux/index.md) and submit the request

**Comment by dsyme** [comment]
@davidpodhola Did you send a PR for this?  I notice you fixed it in your local repo

**Comment by davidpodhola** [comment]
@dsyme oops, note, sorry, created https://github.com/fsharp/fsfoundation/pull/484

**Comment by dsyme** [comment]
Thanks!
