### ISSUE TITLE
Unclear which data access libraries are specific to MS SQL Server

### ISSUE THREAD

**Issue by anilmujagic** [fsharp/fsfoundation#412]
I got interested in F# recently and came to following page to see what are my options for accessing data in databases: http://fsharp.org/guides/data-access/#sql-data-access

However, I'm a bit confused because it is not immediately clear which libraries are specific to (and available only for) MS SQL Server, and which are usable with other DB systems too.
It seems to me that word "SQL" is used in some parts of that text as a synonim for MS SQL Server, but it is not clear for which libraries.

I suggest to explicitly mark MS SQL Server specific libraries, so it is immediately clear what are the options for someone using other DB system (e.g. PostgreSQL).

If I (as an F# newbie) misunderstood something, then I apologize in advance.

**Comment by dsyme** [comment]
I clarified this in the guide
