### ISSUE TITLE
"Email1 has already been taken" when password is too long at activation

### ISSUE THREAD

**Issue by philderbeast** [fsharp/fsfoundation#436]
I have an existing twitter account rego with the fsharp org but with no email in the private settings. I then went to join the foundation. I chose email as the method and on validating via the emailed link, I get to choose a password. Using a password manager, the password of 100 chars is greater than the allowed 45 chars and the activate account step failed. Now I am stuck in this situation.

I have a twitter rego with a username I cannot associate an email with because the email I want to use is taken ...

Label: Hi <name>, thanks for joining!
Error: Email1 has already been taken
Field: [email address]

I have an email account that is not validated for which I cannot generate a forgotten password link ...

Caption: Reset your password
Error: Email does not have an account
Field: [email address]
Button: Send password reset instructions

Note that the username I chose at the email activation step was the same as the one associated with the twitter rego. No error was shown regarding the username being taken already.

**Comment by ReedCopsey** [comment]
Phil,

You managed to get two accounts setup, which was causing the system to go a bit crazy.  I've merged the two - if you login via twitter, you should be able to wset your (45 character or less) password and get it all working again.

Let me know if you have any other issues.

**Comment by philderbeast** [comment]
I see you have put the email I'd like in the private settings of the twitter account. I tried the password reset as you suggested but it fails.

Page: https://fsharp.nationbuilder.com/users/password_resets/new

Caption: Reset your password
Error: Email does not have an account
Email: [email address]
Button: Send password reset instructions

This should be reproducible if you know the email address I'm using.

**Comment by ReedCopsey** [comment]
@philderbeast I just deleted your account - if you can, just setup a new one using your email, then add your twitter to it afterwards (I know that works very cleanly).  Provided you don't try a 100 character PW, hopefully this will resolve it permanently. ;)  Sorry for the problems.

**Comment by philderbeast** [comment]
Thanks Reed that works for me.
