### ISSUE TITLE
Need Help w. F# File.

### ISSUE THREAD

**Issue by sburr100** [fsharp/fsfoundation#441]
Can someone please tell  me why I cannot get this Visual F# file to compile successfully?? The problem seems to be the last line : Console.ReadKey(true) I do n't see for the life of me what could be wrong with it.
// Learn more about F# at http://fsharp.org

 #light

 open System
 
 Console.WriteLine("Please Press 1")
 Console.WriteLine("Please Press 2")
 Console.WriteLine("Please Press 3")
 let input = Console.ReadLine()
 //set up conditional expression on the condition that the response is true.
if input.Equals("1") then
     Console.Write "Hey you must be Steven!"
elif input.Equals("2") then
     Console.Write "Hey you must be Markie!"
else  
     Console.Write "Okay you must have hung up!"
Console.ReadKey(true)

**Comment by mavnn** [comment]
Hi @sburr100 !
This repository stores the fsfoundation web site, so it's probably not the best venue for this type of question.

Can I suggest asking on [StackOverflow](http://stackoverflow.com/) with the F# tag, on [the F# Open Source mailing list](https://groups.google.com/forum/#!forum/fsharp-opensource) or in the F# room at [Functional Programming Slack](http://fpchat.com/) (unfortunately, this last option requires you to request an invite). All three places tend to respond very rapidly to questions, especially for people just getting started at F#.

Unfortunately, it's a little hard to see why the code fails here as the comment markup has removed your indentation.
