### ISSUE TITLE
The language specification for F# 2.0 is not freely accessible

### ISSUE THREAD

**Issue by mexx** [fsharp/fsfoundation#458]
As Scribd require the user to register to see or download the whole document, it would be cool to have the language specification for F# 2.0 also hosted directly on fsharp.org, like the ones for newer versions.

**Comment by voronoipotato** [comment]
Is this still on scribd? Is there a good reason we couldn't move this to the github on a branch if it's massive?

**Comment by dsyme** [comment]
We've moved on a long way from F# 2.0 so closing this out
