### ISSUE TITLE
F# 4.0 without VS and MSBuild 14

### ISSUE THREAD

**Issue by opestov** [fsharp/fsfoundation#470]
Comment on "Option 3: Install the free F# compiler and tools alone"

Visual F# Tools 4.0 needs MSBuild 14 and it is not part of the Framework 4.6 or Windows 10 SDK. After installing SDK and F# the following error appears when I run fsi.exe or fsc.exe: `error FS0193: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

I had to additionally install Microsoft Build Tools 2015 to fix this issue. I think it should be mentioned on the installation page (link to download build tools: https://go.microsoft.com/fwlink/?LinkId=615458).

**Comment by forki** [comment]
Yes I noticed that too. Please send a pull request with making that clear

**Comment by forki** [comment]
Also it would be nice if the installer in F# vnext could handle this. /cc @latkin

**Comment by dsyme** [comment]
Yes, please send a PR for this? thanks
