### ISSUE TITLE
Pluralsight course link(s)

### ISSUE THREAD

**Issue by ploeh** [fsharp/fsfoundation#474]
On Twitter, @dsyme [suggests](https://twitter.com/dsyme/status/631763818012635136):

> don't forget to make sure all the courses are listed on http://fsharp.org/training/

Some (3) courses are already listed there. Should we keep on adding individual entries to this list, or should we instead link to the Pluralsight search page that contains all the courses tagged with _F#_: http://www.pluralsight.com/search/?searchTerm=F%23

Personally, Pluralsight is business for me, so I certainly wouldn't mind if the page lists all five of my courses, but if we were to list all current F# Pluralsight courses, it would be 9 or 10 courses already. Wouldn't it drown out the other commercial offerings listed on that page?

I'll be happy to send a pull request either way, but wanted to ask about the preferred policy first.

**Comment by misterspeedy** [comment]
I'll tackle this as part of https://github.com/fsharp/fsfoundation/issues/342. (Kit)

**Comment by dsyme** [comment]
Closing out this old issue
