### ISSUE TITLE
HTML5 warnings

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [fsharp/fsfoundation#496]
Hello,

It would be nice to fix all HTML5 warnings and errors.
https://validator.w3.org/nu/?doc=http%3A%2F%2Ffsharp.org%2F

What is the pull request policy? I can create new branch or I need to fork project?

**Comment by tpetricek** [comment]
Can you do the changes in a fork of the repository in your profile? Than you can send a pull request and we can merge it.

**Comment by lukasz-pyrzyk** [comment]
Sure, working on it.

**Comment by lukasz-pyrzyk** [comment]
Merged.
