### ISSUE TITLE
Adding Ionide to the Getting Started Page

### ISSUE THREAD

**Issue by cloudRoutine** [fsharp/fsfoundation#511]
I'd like to add [Ionide](http://ionide.io/) to the [getting started on windows](http://fsharp.org/use/windows/) page. 

Should Option 3 be rewritten as these instructions apply to using F# with all of the alternative editor plugins (sublime, vim, emacs, etc)

@tpetricek has suggested that all the getting started instructions could be coalesced into one page. I think that would be nice if it included a sidebar for navigation and proper anchor tags.

**Comment by tpetricek** [comment]
I think adding Ionide to the individual pages would definitely make sense.

My thinking around a single "getting started page" was that the current "use" pages are very technical, so a simpler landing page with links to the "use" pages could be nice.

**Comment by dsyme** [comment]
This has been done
