### ISSUE TITLE
Mentorship page status updated broke

### ISSUE THREAD

**Issue by ReedCopsey** [fsharp/fsfoundation#523]
@swlaschin and Andrea - the latest PR for updates on mentorship has some issues:

- Links are broken (for example, link to http://fsharp.org/mentorship/about.md , which is 404, etc - In general, all links need to go to `.html` instead of `.md`)
- Should contacts include email to education@fsharp.org in addition (instead of?) the twitter contact?

**Comment by swlaschin** [comment]
Oops. My mistake -- I will fix and submit another PR.
