### ISSUE TITLE
Suggestion: Add Type Provider List Page

### ISSUE THREAD

**Issue by jwood803** [fsharp/fsfoundation#525]
Was giving a small F# presentation to colleagues the other day and I realized there was no list of F# type providers to quickly show folks what all is out there (that I could find, anyway). @sergey-tihon has a bit of a list [in a blog post here](https://sergeytihon.wordpress.com/2013/08/05/f-type-providers-news-from-the-battlefields/) but it is almost two years old now.

Perhaps we can have a list on the site that can be constantly updated? Or is this even worth having in the first place?

If y'all agree it can be worth having, I can go ahead and start on a list for a PR.

**Comment by sergey-tihon** [comment]
As I remember, last time, we agreed to reference them in appropriate sections of http://fsharp.org/ guides together with other F#-related projects.

**Comment by dsyme** [comment]
They are listed in community projects.
