### ISSUE TITLE
suggest: my two of syntax sugars

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fsfoundation#527]
i have two syntax sugar:
first, current code:
    let i:int = try int.parse(str) with _ -> 0
syntax sugar is:
    **let i:int = int.parse(str) orelse 0**

second,current code:
____for item in anycollection do
________match item with
________| ... when ... -> ..
________| _ -> failwith ""
syntax sugar is:
____**through anycollection each**
____| ... when ... -> ..
____| _ -> failwith ""

**Comment by ReedCopsey** [comment]
F# Language suggestions should be directed to the [F# User Voice site](https://fslang.uservoice.com/) pages.  Please post each of these there.
