### ISSUE TITLE
Use Fsharp on Linux/Debian outdated

### ISSUE THREAD

**Issue by pakanek** [fsharp/fsfoundation#532]
Instructions on [fsharp.org](http://fsharp.org/use/linux/) are incomplete. If you add repository and try to install mono-complete and fsharp, package manager will fail because of dependencies. Original page at [mono-project.com](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives) clearly states that you need additional repositories for Debian 8 and later, but fsharp.org doesn't mention this.

**Comment by dsyme** [comment]
@pakanek Can you send a PR to update the instructions please?

@tpetricek @ReedCopsey Can we arrange regular QA and updating of these instructions please?
