### ISSUE TITLE
Broken link: "Install .NET 4.5"

### ISSUE THREAD

**Issue by knocte** [fsharp/fsfoundation#534]
This is a broken link: http://www.microsoft.com/net/downloads

It is used in this page:
https://github.com/fsharp/fsfoundation/blame/gh-pages/use/windows/index.md#L55

**Comment by dsyme** [comment]
Hi @knocte, Could you send a PR to fix this please?  Thanks!

**Comment by knocte** [comment]
Didn't send one yet because I don't know the correct link :)

**Comment by dsyme** [comment]
Probably https://www.microsoft.com/en-au/download/details.aspx?id=30653

**Comment by dsyme** [comment]
Or better https://msdn.microsoft.com/en-us/library/5a4x27ek(v=vs.110).aspx
