### ISSUE TITLE
Speaker program under wrong section

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsfoundation#546]
The "F# Speakers Program" looks like it's under the wrong section.  "Learn" should be where people go to learn the basics of F# - just like the "learn" section of other programming language websites.  The Speakers program should probably go under "Contribute" or "Foundation" or a new "Community" tab.

The Mentors program also looks like it is too high up the list.  

![menus](https://cloud.githubusercontent.com/assets/7204669/15011023/6f1d3774-11e7-11e6-8d9d-bd625a0a5d6f.PNG)

**Comment by voronoipotato** [comment]
Yep that definitely looks like the wrong section. Contribute sounds fine.

**Comment by voronoipotato** [comment]
https://github.com/fsharp/fsfoundation/pull/773
