### ISSUE TITLE
Is registry required on FreeBSD install?

### ISSUE THREAD

**Issue by LesF** [fsharp/fsfoundation#556]
The instructions at: http://fsharp.org/use/freebsd/  suggest setting access rights after installing.
`chmod -R 777 /usr/local/etc/mono/registry`
but the registry directory does not exist after a fresh install of the port.
Should this directory be created for future use, does something else create it when needed, or has this registry been moved elsewhere in a more recent version?

**Comment by dsyme** [comment]
Closing out this old Mono-related issue
