### ISSUE TITLE
Improvements to learning page

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/fsfoundation#558]
http://fsharp.org/about/learning.html

My working ideas:

1) indicate that try fsharp requires Silverlight and move below .Net fiddle

2) add to list the newly create Visual F# Development Portal https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/visual-fsharp-development-portal 

3) evaluate other interactive sites suggested

**Comment by dsyme** [comment]
I think that's all fine. Though we really urgently need a replacement for tryfsharp that's dedicated specifically to F# learning.

It would be great if the canonical landing url for learning were http:fsharp.org/learn. You can do that without breaking things via  redirects

**Comment by smoothdeveloper** [comment]
http://learn.fsharp.org

**Comment by jackfoxy** [comment]
I have some simple changes to the page ready, but as for implementing a redirect, does anyone know how to get a markdown page to render javascript? The best I can figure out from a PR is to submit a new learn page in the root that will render the following. May have to get the webmaster involved to do this.

````
<script>
window.location.replace('/about/learning.html')
</script>
````

**Comment by ReedCopsey** [comment]
Jack,

You can use redirect-from:
https://help.github.com/articles/redirects-on-github-pages/

We do it elsewhere on the site- it's probably a better approach than using
javascript to redirect.

**Comment by jackfoxy** [comment]
https://github.com/fsharp/fsfoundation/pull/560

**Comment by jackfoxy** [comment]
#560 complete
Last step PR to update Learn F# link in core-net docs to point to learn page https://github.com/dotnet/core-docs/pull/465

**Comment by jackfoxy** [comment]
Thanks to our friends in the .NET Core project we now have good links to F# documentation from their docs https://dotnet.github.io/docs/ , the original goal of this issue.

Closing
