### ISSUE TITLE
Remove FunScript from JS/HTML 5 guide?

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/fsfoundation#582]
I don't feel I'm entitled to remove FunScript from the options to translate F# to JS. However, as the project is not maintained anymore I'm afraid it can be a bit frustrating for new users if they become aware of the fact after spending some time to decide between, say, FunScript and Fable.

**Comment by tpetricek** [comment]
Maybe we could add a note saying "(No longer actively maintained)" for now - that should be enough to navigate new people towards one of the active projects, but it still acknowledges FunScript's contribution & existence.

**Comment by ReedCopsey** [comment]
I merged this- but do question whether the guide should have it at all if it's not maintained.  I know Fable's pages mention it (so there's still acknowledgement), but a "Guide" should be somewhat a "this is a good idea" - 

Is it really a good idea to refer people to FunScript now that Fable has reached the level its currently at now?

**Comment by tpetricek** [comment]
@ReedCopsey I think both me and @alfonsogarciacaro are conflicted to make the decision. But if you think it is better to remove FunScript, then feel free to do so.
