### ISSUE TITLE
Option 2 on "Use F# on Mac OSX" seems to be missing a step

### ISSUE THREAD

**Issue by zanedp** [fsharp/fsfoundation#592]
http://fsharp.org/use/mac/

Option 2 seems to assume you've already done Option 3: Step 1 of option 2 ("Install Visual Studio Code for Mac") doesn't install Mono, but step 2 assumes you've got Mono.

**Comment by brettcannon** [comment]
I came across this as an issue as well. Maybe Visual Studio Code used to install Mono itself and now it doesn't? Either way the docs do not seem to match the current situation.
