### ISSUE TITLE
Discussion: PascalCase vs camelCase in record fields

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsharp/fsfoundation#600]
It seems to me that the [design guidelines](http://fsharp.org/specs/component-design-guidelines/#do-use-the-net-naming-and-capitalization-conventions-for-object-oriented-code-including-f-facing-libraries) are not taking an explicit stance on this issue. Let's discuss here and see what could be amended.

**Comment by eiriktsarpalis** [comment]
Personally, I'm in favor of using PascalCase for a number of reasons:
* Record fields are compiled as properties, which otherwise adhere to PascalCase in all contexts.
* Union case constructors already enforce PascalCase, so it becomes unsightly when you mix casings in record/union combinations.
* Many popular F# libraries out there use PascalCase, for instance FAKE. I haven't sampled sufficiently though, we could do that in this thread.

**Comment by voronoipotato** [comment]
PascalCase sounds good to me. Do you object @dsyme?

**Comment by dsyme** [comment]
Closing out this old issue

I personally use PascalCase.

The component spec is now here: https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines

We can discuss in an update the component spec by editing it directly there and sending a pull request?
