### ISSUE TITLE
Option 4: (CentOS) at "use/linux" must be updated

### ISSUE THREAD

**Issue by AlexSugak** [fsharp/fsfoundation#611]
Current description points to "haf/oss" package which does not work anymore.
(looks like the problem is that it uses "mozroots" which is [not supported](https://github.com/KSP-CKAN/CKAN/issues/1787))

Since there are official packages for mono and fsharp [available from mono repository](http://www.mono-project.com/docs/getting-started/install/linux/), 
I think fsharp documentation should point to it as a default way to have mono/fsharp running on RHEL, CentOS etc.

E.g. this should be enough:

```
yum install yum-utils
rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
yum-config-manager --add-repo http://download.mono-project.com/repo/centos/
yum -y install mono-complete
yum -y install fsharp
```

If this is OK, I can submit a PR to fix the documentation.

**Comment by dsyme** [comment]
Yes, please submit a PR
