### ISSUE TITLE
dead link in "Use F# for GPU Programming"

### ISSUE THREAD

**Issue by nestordemeure** [fsharp/fsfoundation#617]
The  StatFactory FCore [link](http://www.statfactory.co.uk/) on the F# for GPU [page](http://fsharp.org/use/gpu/) appears to be dead.

I don't know what the current status of the project is but I was only able to found some blob [posts](https://statfactory.wordpress.com/) a [talk](https://skillsmatter.com/skillscasts/7097-numerical-computing-with-f-sharp-and-mkl) and a [GitHub](https://github.com/telefunkenvf14/FCore) (probably not the original one).

**Comment by dsyme** [comment]
Thanks!
