### ISSUE TITLE
broken NEWS link on main home page 

### ISSUE THREAD

**Issue by goswinr** [fsharp/fsfoundation#621]
The News link on the main home page just shows some raw xml for me ( on latest chrome)

**Comment by goswinr** [comment]
http://fpish.net/rss/blogs/tag/1/f~23 shows raw xml for me

**Comment by AlexStory** [comment]
this was after the api used to pull news feed war removed, I assume temporarily the feed was directly consumed, but this is not a current issue. 

Can this be closed?

**Comment by goswinr** [comment]
probaly yes, I can only test it when the PR is merged, no ?
