### ISSUE TITLE
Broken link on Teaching F#

### ISSUE THREAD

**Issue by selketjah** [fsharp/fsfoundation#624]
If you go to [Teaching F#](http://fsharp.org/teaching/index.html) and scroll down to "Lectures and course material" the first link "Introduction to functional programming" is no longer available and gives you a 404 Page not found.

Lectures and course material links to: [http://tomasp.net/materials/mff-fsharp-09/](http://tomasp.net/materials/mff-fsharp-09/)

**Comment by ReedCopsey** [comment]
@tpetricek Is it possible to get the content restored on your site?  Has the URL changed?

**Comment by smoothdeveloper** [comment]
@ReedCopsey / @selketjah looks like http://tomasp.net/academic/materials/mff-fsharp-09/

**Comment by smoothdeveloper** [comment]
@tpetricek might have done some SEO figuring that adding "academic" would yield lot more visits ;)

**Comment by ReedCopsey** [comment]
Fixed in #625
