### ISSUE TITLE
Cannot sign in with Facebook: app still in development mode

### ISSUE THREAD

**Issue by lilred** [fsharp/fsfoundation#631]
To reproduce:

1. Go to fsharp.org -> foundation -> join
2. Click "create an account or log in"
3. Click on the Facebook icon
4. Witness the following error in Facebook: "App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."
5. Witness the following error in fsharp.org: "There was an error trying to log you in with Facebook"

**Comment by baronfel** [comment]
I cannot reproduce this at the moment, can you try again?

**Comment by voronoipotato** [comment]
@lilred were you able to reproduce this?

**Comment by lilred** [comment]
Nope, this is fixed.
