### ISSUE TITLE
Component design guidelines: incorrect info on NoEquality/NoComparison

### ISSUE THREAD

**Issue by yawaramin** [fsharp/fsfoundation#634]
In the [Component Design Guidelines](http://fsharp.org/specs/component-design-guidelines/), section 5.1, we have the following passage:

> F# record types compile to a simple .NET class. These are suitable for some simple, stable types in APIs. You should consider using the [&lt;NoEquality&gt;] and [&lt;NoComparison&gt;] attributes to suppress the automatic generation of interfaces.

... with a corresponding code example showing how an F# type with these attribute markers is represented in C# without equality and comparison methods.

However, this information is incorrect: see http://stackoverflow.com/q/42656143/20371

My question is, how should we update this section to make it clear that other CLR languages will not honour the F# `NoEquality`/`NoComparison` attributes?

**Comment by dsyme** [comment]
The component spec is now here: https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines

Please update the component spec by editing it directly there and sending a pull request
