### ISSUE TITLE
News section is blank because the API call to populate it is deprecated

### ISSUE THREAD

**Issue by baronfel** [fsharp/fsfoundation#638]
the response from the api server for the request we send is now:

```
$.ajax({
  url: 'http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=10&callback=?&q=http%3A%2F%2Ffpish.net%2Frss%2Fblogs%2Ftag%2F1%2Ff~23',
  dataType: 'json',
  success: function (data) {
      console.log(data);
  }
});
```

```
{ responseData: null
  responseDetails : "This API is no longer available."
  responseStatus: 403 }
```

We should find another way to load RSS data.

**Comment by ReedCopsey** [comment]
In general, finding a better way to aggregate and display RSS would be nice.  We've currently been relying on fpish.net's feed, but using our own aggregation would be better in the long run, especially since we could keep it to just "F#" and more relevant sources.

**Comment by mathias-brandewinder** [comment]
Obviously we need another F# Azure Function ;)
