### ISSUE TITLE
RSS Feed isn't displaying summary

### ISSUE THREAD

**Issue by ReedCopsey** [fsharp/fsfoundation#647]
@AlexStory I merged your PR (#645), but commented out the entry line. It was creating a large block of unescaped, "raw HTML" to show up for feeds, as the entire content was being dumped into the main display.

I don't see how to easily get a summary text for a one liner under the title, using what RSS to JSON returns. Thought I'd open the issue in case anybody sees a nicer way to handle this.

In the meantime, having the feed in place again, but just showing blog titles seems like a reasonable workaround.

**Comment by dsyme** [comment]
Closing this old discussion
