### ISSUE TITLE
Microsoft Build Tools 2015 is not available by given link

### ISSUE THREAD

**Issue by tabakerov** [fsharp/fsfoundation#653]
[Use F# on Windows](http://fsharp.org/use/windows/) has a link to MS Build Tools 2015 which goes to 404. I've found MS Build Tools located under [the link](https://my.visualstudio.com/Downloads?q=build%20tools%202015) but I'm not sure if that makes sense, because it requires some kind of subscription.

**Comment by dsyme** [comment]
THis has been fixed recently
