### ISSUE TITLE
use/Windows code example is wrong.

### ISSUE THREAD

**Issue by cmbrown1598** [fsharp/fsfoundation#656]
Option 4, Item B, Section 4. Powershell code is incorrect. 

When we run the Powershell code on Windows Server 2K8r2, we get a message "Program 'FSharp_Bundle.exe' failed to run: The specified executable is not a valid application for this OS platform."

---

Recommend simply downloading the file and keeping the name, and then simply running msiexec instead.  Example:

Invoke-WebRequest -Uri "http://download.microsoft.com/download/F/3/D/F3D6045E-4040-4058-ADAD-2698F1793CBC/Microsoft.FSharp.SDK.Core.msi" -OutFile "$pwd\Microsoft.FSharp.SDK.Core.msi"
msiexec /i Microsoft.FSharp.SDK.Core.msi /quiet

**Comment by dsyme** [comment]
Fixed by https://github.com/fsharp/fsfoundation/pull/660, thanks
