### ISSUE TITLE
Headings are cramped

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsfoundation#666]
Markdown/CSS/HTML thing: we need to add padding space before all the headings in the guides - the appearance is too cramped.  Too often we are using the

    <br /> <br />

hack to get space, e.g. https://github.com/fsharp/fsfoundation/blame/gh-pages/guides/web/index.md#L52

We also need to make sure anchors work correctly even when the navbar is there. 

I tried various permutations on the padding/margin trick for anchors but couldn't get any extra space to appear https://github.com/fsharp/fsfoundation/blob/47d13f9bc1aea673d29295033813df8612c27375/css/main.css#L38

**Comment by ReedCopsey** [comment]
What browser/OS are you using?  Web guide, for example, appears to have
plenty of space (honestly, too much in most places), on chrome/windows.

**Comment by dsyme** [comment]
@ReedCopsey That's because it is using the 

    <br /> <br />

hack.  I think one br would be about right, but it would be better  in the CSS to ensure consistency

**Comment by ReedCopsey** [comment]
It's not at the bottom, which looks fine, though.

**Comment by dsyme** [comment]
@ReedCopsey I put in explicit 

----

lines there

**Comment by FSSF** [comment]
Thanks Don - This is all getting reworked at the moment by the new web team, so I wouldn't stress too much about minor visual tweaks right now.
