### ISSUE TITLE
Visual Studio Build Tools 2017 15.2 does not contain F# option

### ISSUE THREAD

**Issue by colinbowern** [fsharp/fsfoundation#668]
On http://fsharp.org/use/windows/ there is a note under Option 4A:

> Starting with Visual Studio 2017 Update 3, F# is an optional component. Simply select F# from the Individual Components tab and press Install.

However the Visual Studio Build Tools 2017 15.2 (26430.14) doesn't include an option for F# under Individual components. This has also been noted here -- https://stackoverflow.com/questions/42679193/install-f-4-1-sdk-on-build-server

The 15.3 Build Tools do not appear to be available with the changes to Visual Studio's new Preview channel. The link to download the preview version of the tools on https://github.com/Microsoft/visualfsharp/issues/2553 is no longer working.

**Comment by cartermp** [comment]
> However the Visual Studio Build Tools 2017 15.2 (26430.14) doesn't include an option for F# under Individual components.

This is because the VS Build Tools are for Update 2 (15.2 --> Visual Studio 2017 Update 2).  I seems that Update 3 has not shipped yet.  Unfortunately, there's not much to do here until that ships.

> The link to download the preview version of the tools on Microsoft/visualfsharp#2553 is no longer working.

Which link?  The links to both the F# 4.1 Compiler Tools NuGet and the F# 4.1 Compiler SDK is live and works - just tested.

**Comment by piers7** [comment]
Now that VS 2017.3 [is out](https://blogs.msdn.microsoft.com/visualstudio/2017/08/14/visual-studio-2017-version-15-3-released/), the separate build tools installer (now 15.3.2) **does** now have the F# compiler and SDK included.

Putting this on my build server has now fixed my build to work under MSBuild 15, using F# 4.1 language features that previously wouldn't build under MSBuild 14/F# 4.0. I've not tried this on an entirely clean machine yet, but from everything I see in the logs it has worked.

Download page for build tools: https://www.visualstudio.com/downloads/

**Comment by dsyme** [comment]
@piers7 That's great to know 

@cartermp  Is http://fsharp.org/use/windows now up-to-date? Thanks

**Comment by cartermp** [comment]
Should be up to date, yes.
