### ISSUE TITLE
Potentially Link to Tomas' Tracking page for Board Member goals

### ISSUE THREAD

**Issue by baronfel** [fsharp/fsfoundation#670]
Tomas has a page at https://the-fsharp-mirror.github.io/ where he's keeping tabs on the goals that each of the 2017 Board Members set in the FSSF Slack. We should link to this in some way to show what we've been up to.

**Comment by voronoipotato** [comment]
Requesting close for this issue. The last update was October 2017, nearly 2 years ago.
