### ISSUE TITLE
Have a single http://fsharp.org/use that detects platform - via @dsyme

### ISSUE THREAD

**Issue by FSSF** [fsharp/fsfoundation#681]
@dsyme wrote in the Ask the Board repo:

> The "install F#" experience is clunky, and there is no single URL to point people to like http://fsharp.org/use. (I point people to http://fsharp.org instead). This URL should detect platform and make a default one-click install link available for the #1 option for linux/mac/windows/..., plus other options

---

Migrated from https://github.com/fsharp/fssf-ask-the-board/issues/3

**Comment by dsyme** [comment]
Closing this out as feedback into #680
