### ISSUE TITLE
The fsharp.org website should show some code - via @julienXX

### ISSUE THREAD

**Issue by FSSF** [fsharp/fsfoundation#682]
@julienXX wrote in the Ask the Board repo:

> F# is beautiful IMO and the website should show some basic code on the main page in order for users to get a glimpse of it. See rust-lang.org or haskell.org for example.

---

Migrated from https://github.com/fsharp/fssf-ask-the-board/issues/2

**Comment by pmbanka** [comment]
I think that Pyret language does this really well on their website: https://www.pyret.org/

I saw the language mentioned in the passing somewhere and by scrolling the main page I could figure out what this language is all about. I think that especially "Highlights vs. Existing Languages" section is very useful and informative.

Note that these examples are not runnable - but there is a quick link to Try Pyret on top.

Also note that this site works really well on mobile.

**Comment by dsyme** [comment]
Covered by #680, closing this out as feedback into that process
