### ISSUE TITLE
Taking an opinionated approach to getting started with F# - via @cartermp

### ISSUE THREAD

**Issue by FSSF** [fsharp/fsfoundation#683]
@cartermp wrote in the Ask the Board repo:

> This pertains to the FSSF site, which is usually the first one people go to when they're learning F# for the first time.

> I believe that one of the bigger blockers to F# (and .NET) adoption is twofold:
>
>    There are many ways to get started.
>   It's not clear which is the best if you're a newcomer to F# (or .NET).

> I think the best way to solve this is to take an opinionated stance on what people should use to get started, then link to a page which offers all the other alternatives.

---

Migrated from https://github.com/fsharp/fssf-ask-the-board/issues/1

**Comment by voronoipotato** [comment]
@Krzysztof-Cieslak @cartermp You were involved on this discussion. Is this still a goal we have? If not perhaps we should close this issue.

**Comment by ReedCopsey** [comment]
@voronoipotato I think this should be brought up to the Board - perhaps in the July meeting, to discuss. I think this is a valuable long term goal for FSSF to have, though.

**Comment by voronoipotato** [comment]
Sounds good. Just wanted to make sure it didn't fall into the Lethe.
