### ISSUE TITLE
Donate tab is not available from the main page

### ISSUE THREAD

**Issue by eugene-g** [fsharp/fsfoundation#707]
http://fsharp.org/ and http://foundation.fsharp.org/ are having different set of tabs, which could have its own reasons, but it feels that Donate tab should belong to the main page.

**Comment by ScottHutchinson** [comment]
In addition to a donate link on the main page, there should be a link on the Contribute menu, which might be where some people would look for it.

**Comment by dsyme** [comment]
Fixed
