### ISSUE TITLE
F# Tools linking to v4.0 instead of v4.1 for Windows

### ISSUE THREAD

**Issue by haf** [fsharp/fsfoundation#722]
http://fsharp.org/use/windows/

Furthermore, this page doesn't explain how to get F# intellisense working when someone's clicked through the default VS 2017 Community installer. Opening an F# file in that setting, shows no highlighting. Then https://github.com/Microsoft/visualfsharp/issues/2794 may be the solution; but that should be documented at the above page IMO.

When googling, the next reference seems to be https://marketplace.visualstudio.com/items?itemName=VisualFSharpTeamMSFT.MicrosoftVisualFTools which markets F# 3.1. Consider removing or updating the description of this link.

**Comment by dsyme** [comment]
Closing this old issue, these pages have been rewritten recently
