### ISSUE TITLE
Use HTTPS for the site.

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsharp/fsfoundation#724]
[This](https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b) is a good guide.

**Comment by ReedCopsey** [comment]
This is now done, since Github pages now supports https directly.

**Comment by teo-tsirpanis** [comment]
Nice to hear. 😊 You can also update the project link.

![image](https://user-images.githubusercontent.com/12659251/39515018-80c0b764-4e01-11e8-88bc-ee0e8fa326a1.png)

**Comment by ReedCopsey** [comment]
Fixed - thanks @teo-tsirpanis
