### ISSUE TITLE
FsLab

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fsfoundation#726]
Is there any specific reason, why FsLab is not in this list, or can I contribute a couple of lines about it?

https://github.com/fsharp/fsfoundation/blob/gh-pages/guides/machine-learning/index.md

Seems the default/primarily way to do ML on F#?

**Comment by tpetricek** [comment]
I think there is also "data science" guide and FsLab fits better with that, but I completely agree that it is relevant to ML too - I think if you send a PR adding it to the list (in some way that does not make the guide confusing) then it would make sense to accept it :)

**Comment by voronoipotato** [comment]
@ShalokShalom If you don't submit a PR could you share with me what you hoped to add so that we can add it?

**Comment by ShalokShalom** [comment]
I have no preference about that. I just recognized it's not on the list and that it could be. Sorry, I seem to forgot about this issue, you can surely add FsLab in what ever fashion you like, I would simply see if I find some link and information in the Internet and add that. Is that fine to you both? :)

**Comment by ShalokShalom** [comment]
I have no preference about that. I just recognized it's not on the list and that it could be. Sorry, I seem to forgot about this issue, you can surely add FsLab in what ever fashion you like, I would simply see if I find some link and information in the Internet and add that. Is that fine to you both? :)

**Comment by dsyme** [comment]
Closing this old issue
