### ISSUE TITLE
Fsharp.Core version = 4.4.1.0 can not be assembled

### ISSUE THREAD

**Issue by PalindromeLeung** [fsharp/fsfoundation#728]
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I have fsharp installed and it keeps complaining that it cannot find the right version.
Anyone has the same issue ?

**Comment by harrysame** [comment]
Oh I actually got this problem resolved. 
Use home-brew to install mono and then overwrite all the conflict files using the cmd below. 
------------------------------------------------
Hannahs-MacBook-Pro: isprime$ brew install mono
Warning: mono 5.4.1.6 is already installed, it's just not linked
You can use `brew link mono` to link this version.
Hannahs-MacBook-Pro:Platypus isprime$ brew link mono
Linking /usr/local/Cellar/mono/5.4.1.6... 
Error: Could not symlink share/man/man1/al.1
Target /usr/local/share/man/man1/al.1
already exists. You may want to remove it:
  rm '/usr/local/share/man/man1/al.1'

To force the link and overwrite all conflicting files:
  brew link --overwrite mono

To list all files that would be deleted:
  brew link --overwrite --dry-run mono
-----------------------------------------

It's a linking problem and there are conflicting files. So I used the 
` brew link --overwrite mono` 
and
`brew link --overwrite --dry-run mono`
Hooray!
