### ISSUE TITLE
Update Board/Officers

### ISSUE THREAD

**Issue by baronfel** [fsharp/fsfoundation#738]
This page is out of date as far as I can see: http://foundation.fsharp.org/board_and_officers

It needs the new board members from the 2018 election.

**Comment by StachuDotNet** [comment]
@ReedCopsey I can't seem to find the "Officers and Trustees" page anywhere in this repo. Is this editable via a PR?

**Comment by baronfel** [comment]
@StachuDotNet it _may_ live over in NationBuilder, now that I'm thinking about it. I think everything under `foundation.fsharp.org` comes from there.

**Comment by baronfel** [comment]
@ReedCopsey @mathias-brandewinder ping, do you fine gentlemen have any insight into what we have to do here?

**Comment by ReedCopsey** [comment]
Mostly just get time to fix the pages. My life is upside down atm, so I
haven't been able to yet. Sorry...

**Comment by mathias-brandewinder** [comment]
I updated the list, and the historical list:
http://foundation.fsharp.org/board_and_officers
http://foundation.fsharp.org/board_and_officer_history
Note: we still need to update the pictures and bios for the board members on the first page.

**Comment by StachuDotNet** [comment]
Ping @mathias-brandewinder @ReedCopsey This can be closed. We have an issue elsewhere regarding the bios/pictures.
