### ISSUE TITLE
Dead link: http://www.tryfsharp.org/Learn/financial-computing

### ISSUE THREAD

**Issue by ldw** [fsharp/fsfoundation#765]

**Comment by voronoipotato** [comment]
Yep this link is super dead.

**Comment by voronoipotato** [comment]
https://github.com/fsharp/fsfoundation/pull/772

**Comment by coryBove** [comment]
This link still shows up on the home page:

https://github.com/fsharp/fsfoundation/blob/9c5ed86e74e270de60c3128b1b59cab8c05c21a3/index.html#L150
