### ISSUE TITLE
I am finding the site frustrating.

### ISSUE THREAD

**Issue by gdennie** [fsharp/fsfoundation#825]
Presently I am looking for library information on native F# data structures like `map` and `list` and `option`. There is no search feature and the know place to look apart from random clicking around.

I am making a note here before I eventually find it somewhere else.

I was also unable to find reasonable info for accessing libraries for fsharp scripts, paket vs nuget vs dotnet for scripts, and such. There aught to be current curated recipes for all various platforms from the numerous brilliant minds out there doing this stuff day in and day out.

**Comment by dsyme** [comment]
Closing as this feedback is being taken into account in the site redesign, and also relates to the hosting of the docs elsewhere

**Comment by dsyme** [comment]
Closing as this feedback is being taken into account in the site redesign, and also relates to the hosting of the docs elsewhere
