### ISSUE TITLE
F# Compiler Community Session - Learn me the F# Compiler  - An Online Chat with Vlad and Don

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsfoundation#845]
Similar to [the F# Dugnad sessions](https://github.com/fsharp/fsfoundation/issues/827) , on Thursday 17 September 2020, 7pm BST (UK time), @dsyme and @vzarytovskii will be hosting a chat session together and with the community about the F# compiler

**Learn me the F# Compiler  - An Online Chat with Vlad and Don**

Thursday 17 September 2020, 7pm BST (UK summer time)

Topics for our first session

- F# Compiler Guide  and Overview
- Fixing a bug in the F# compiler
- Understanding the F# Optimizer

We will post a teams link here shortly before the call and record/archive the session.  Please join us.

**Comment by ajeckmans** [comment]
Will we be able to view the recording even if we haven't participated?

**Comment by brettrowberry** [comment]
How long do you expect the session to go?

**Comment by dsyme** [comment]
About an hour, maybe a bit more

**Comment by dsyme** [comment]
> Will we be able to view the recording even if we haven't participated?

Yes I believe so. First time we've done this though

**Comment by brettrowberry** [comment]
Did I miss the link?

**Comment by augusto2112** [comment]
@brettrowberry I believe the link will be posted tomorrow.

**Comment by brettrowberry** [comment]
Darn off by one errors! It's tomorrow haha

**Comment by dsyme** [comment]
> Darn off by one errors! It's tomorrow haha

And tomorrow it will be today...

**Comment by shishini** [comment]
@dsyme can you please also post this on https://forums.fsharp.org/ 

please :) 

it looks like a very good candidate as forum post, rather than an issue that needs a fix

**Comment by dsyme** [comment]
> @dsyme can you please also post this on https://forums.fsharp.org/

@shishini Please do post it for us?

**Comment by augusto2112** [comment]
[I've gone ahead and posted it.](https://forums.fsharp.org/t/f-compiler-community-session-learn-me-the-f-compiler-an-online-chat-with-vlad-and-don/1455)

**Comment by shishini** [comment]
> 
> 
> > @dsyme can you please also post this on https://forums.fsharp.org/
> 
> @shishini Please do post it for us?

@augusto2112 did, 
but i was hoping you would have done it 

I keep trying , or hoping to make the forum more popular, if the forum in the future, becomes the primary location of similar posts, it would sure help 

A nice active forum, is a good thing for F#

**Comment by dsyme** [comment]
Live event link is https://teams.microsoft.com/l/meetup-join/19%3ameeting_YzRhNzRmYmUtMzFiNC00ZDZmLWE0MjMtZGRiNjVjZTE4ODVj%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%2c%22IsBroadcastMeeting%22%3atrue%7d

**Comment by nojaf** [comment]
Hey @dsyme, I'm watching the recording and around `0:56:09` you are trying to show the Typed tree of `([| |] : byte array)` inside of sharplab.io but there is only an option show the Syntax tree.

Just wanted to let you know that fantomas-tools has limited support to show the Typed tree. 
[For example](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAUA2gD5g%2BAXTDYARgE8ALrDBUATvKoSAlJBABfIA), if you hit the `Show Typed AST` button.

**Comment by dsyme** [comment]
> I keep trying , or hoping to make the forum more popular, if the forum in the future, becomes the primary location of similar posts, it would sure help. A nice active forum, is a good thing for F#

@shishini I understand, and I really respect your commitment here.   I personally don't use the forums as I follow too many notifications on github already. Likewise I don't follow F# reddit.

**Comment by dsyme** [comment]
> Just wanted to let you know that fantomas-tools has limited support to show the Typed tree. For example, if you hit the Show Typed AST button.

@nojaf Oh that's great!

Could you add all this kind of information to https://github.com/dotnet/fsharp/blob/main/docs/compiler-guide.md?

thanks

**Comment by augusto2112** [comment]
Hi @dsyme and @vzarytovskii!

I really enjoyed this first compiler session, and I think it's a great way of introducing people to the different parts of the compiler, especially since a project of this magnitude looks quite intimidating for a newcomer to contribute to.

So I'm curious to know if there will be a second one?

**Comment by Trigun27** [comment]
> Hi @dsyme and @vzarytovskii!
> 
> I really enjoyed this first compiler session, and I think it's a great way of introducing people to the different parts of the compiler, especially since a project of this magnitude looks quite intimidating for a newcomer to contribute to.
> 
> So I'm curious to know if there will be a second one? I think that would be really awesome, and greatly appreciated by the community 😃

As far as i know it will be a second one and a third one. Devs are gathering information about to discuss on a second meeting

**Comment by vzarytovskii** [comment]
Hey folks, we've just published both of our recordings for compiler community meetup. 
You can find them here: https://www.youtube.com/channel/UCsi00IVEgPoK7HvcpWDeSxQ/videos
If you'll find any issues (typos, or something in the video), please let me know.
