### ISSUE TITLE
F# Compiler Community Session - Understanding the F# Optimizer - An Online Chat with Vlad and Don

### ISSUE THREAD

**Issue by vzarytovskii** [fsharp/fsfoundation#846]
Similar to the previous [F# Compiler Community Session](https://github.com/fsharp/fsfoundation/issues/845) , on Thursday 15 October 2020, 8pm BST (UK summer time), 9pm CEST (European summer time), 10pm MST (Moscow time), @dsyme and @vzarytovskii will be hosting a chat session together and with the community about the F# compiler.

Understanding the F# Optimizer - An Online Chat with Vlad, Don and the community.

Thursday 15 October 2020, 8pm BST (UK summer time), 9pm CEST (European summer time), 10pm MST (Moscow standard time).

Topic for our second session:

Understanding the F# Optimizer

We will post a teams link here shortly before the call and record/archive the session. Please join us.

**Comment by vzarytovskii** [comment]
Here's the teams meeting link:
https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTRlNGQ1NTYtMzJkNS00MmVjLTg5OTItYTM1MTkyNDkwNDE2%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%7do

**Comment by dsyme** [comment]
<div style="margin-bottom:20px;margin-top:24px;"><span style="font-size:24px;color:#252424;">Microsoft Teams meeting</span></div><div style="margin-bottom:20px;"><div style="font-weight:bold;margin-bottom:0px;margin-top:0px;"><span style="font-size:14px;color:#252424;">Join on your computer or mobile app</span></div><a class="me-email-headline" href="https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTRlNGQ1NTYtMzJkNS00MmVjLTg5OTItYTM1MTkyNDkwNDE2%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%7d" rel="noreferrer noopener" style="font-size:14px;font-family:'Segoe UI Semibold','Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif;text-decoration:underline;color:#6264a7;" target="_blank" title="https://teams.microsoft.com/l/meetup-join/19%3ameeting_ytrlngq1ntytmzjkns00mmvjltg5otitytm1mtkyndkwnde2%40thread.v2/0?context=%7b%22tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%7d">Click here to join the meeting</a></div><div style="margin-bottom:4px;"><div style="margin-bottom:4px;"><span style="font-size:14px;color:#252424;font-weight:bold;">Or call in (audio only)</span></div><div style="margin-bottom:4px;"><a href="tel:+420234280539,,925429575# " style="font-size:14px;text-decoration:underline;color:#6264a7;" title="tel:+420234280539,,925429575# " target="_blank" rel="noreferrer noopener">+420 234 280 539,,925429575#</a> <span style="font-size:14px;color:#252424;">&nbsp; Czech Republic, Prague </span></div></div><span style="font-size:14px;color:#252424;">Phone Conference ID: </span><span style="font-size:16px;color:#252424;">925 429 575# </span><div style="margin-bottom:20px;"><a class="me-email-link" href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdialin.teams.microsoft.com%2Ff8f5bdf8-00fc-434e-8e7d-cdbc59d0c53d%3Fid%3D925429575&amp;data=04%7C01%7CDon.Syme%40microsoft.com%7Cd342e602eeb24ee2752e08d8701c4360%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637382614119094631%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=JhK1p7N1dAWgV%2Fgkdp8Y%2FZPdImirNTY1voMck3TLh5w%3D&amp;reserved=0" originalsrc="https://dialin.teams.microsoft.com/f8f5bdf8-00fc-434e-8e7d-cdbc59d0c53d?id=925429575" shash="sUCTDrinS/h7Vkus+4TcTNqh0v/x2JXVWhvOY2D69IyMzBl8Iyy/EEz4/DefSaRI6fK8iulUPfY2A9G1nTcKrbURzOHKPKr/veVkH/fI7lyeoAcgHrCKXW2Z/rWsFcgjdfPo+tV8mUKolVLQkb9d42t2MCzBWO1pkc0SjzzJTyk=" rel="noreferrer noopener" style="font-size:14px;text-decoration:underline;color:#6264a7;font-family:'Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif;" target="_blank" title="https://dialin.teams.microsoft.com/f8f5bdf8-00fc-434e-8e7d-cdbc59d0c53d?id=925429575">Find a local number</a> | <a class="me-email-link" href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmysettings.lync.com%2Fpstnconferencing&amp;data=04%7C01%7CDon.Syme%40microsoft.com%7Cd342e602eeb24ee2752e08d8701c4360%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637382614119104590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=iGYOPW2oyi3IyRoNaZVQnwvPiEPRl9VF4QKDe4CXkqs%3D&amp;reserved=0" originalsrc="https://mysettings.lync.com/pstnconferencing" shash="cE+3yT30pkBhz1MUjUrbgmL8tCi3+O4/7MwdDe30rdFbuSWsLR09LztgoRfYW2SUGObxkx95fdLllRMYo/XwrD28rUpsHzWe6PQNCKSzhnSHrY3Ar4mo2Ku/SkyO8uUWFnOhuW4S1XNvbyrpgljw6QV9Ed6iDPxMD2W/POq6StM=" rel="noreferrer noopener" style="font-size:14px;text-decoration:underline;color:#6264a7;" target="_blank" title="https://mysettings.lync.com/pstnconferencing">Reset PIN</a></div><div style="margin-bottom:24px;margin-top:20px;"><a class="me-email-link" href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FJoinTeamsMeeting&amp;data=04%7C01%7CDon.Syme%40microsoft.com%7Cd342e602eeb24ee2752e08d8701c4360%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637382614119104590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=pP4TTaD78A7d8DZrXeq0wDqMenC6cmZ9CeLAyqiQceo%3D&amp;reserved=0" originalsrc="https://aka.ms/JoinTeamsMeeting" shash="ME0uT6QbhRl1n2CybRkDcJpSaZw3SDYfb1DPI1dfNNlhgi5YZXKGbHSmm+R/+U///eC32zJDYsD1bWZQRtjzkB6sSDNs66VQohA4EzOqBf4OmYRSDoMqMDsHv7Xr9I/7gALGu7YRThtpyJ/1BoKJQljQCx0bWxNuGtMQjgtsZzs=" rel="noreferrer noopener" style="font-size:14px;text-decoration:underline;color:#6264a7;font-family:'Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif;" target="_blank" title="https://aka.ms/jointeamsmeeting">Learn More</a> | <a class="me-email-link" href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2FmeetingOptions%2F%3ForganizerId%3D97f10a8e-3843-4db7-8ef7-f449e82693d7%26tenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47%26threadId%3D19_meeting_YTRlNGQ1NTYtMzJkNS00MmVjLTg5OTItYTM1MTkyNDkwNDE2%40thread.v2%26messageId%3D0%26language%3Den-US&amp;data=04%7C01%7CDon.Syme%40microsoft.com%7Cd342e602eeb24ee2752e08d8701c4360%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637382614119104590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=qUjCC7leg6lQdAZyqTaX4Ctum0dTF08O3z%2BvVBY7R%2Fw%3D&amp;reserved=0" originalsrc="https://teams.microsoft.com/meetingOptions/?organizerId=97f10a8e-3843-4db7-8ef7-f449e82693d7&amp;tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;threadId=19_meeting_YTRlNGQ1NTYtMzJkNS00MmVjLTg5OTItYTM1MTkyNDkwNDE2@thread.v2&amp;messageId=0&amp;language=en-US" shash="d5Vi823QyaHQR+urMwNvh8AEsbcb/ioVWskLbooCfDXfrknnOgyw+5EKujiMF+7orlKXclqtfh5goECSlHzUQqoDPrLg7Avn8ufI6pHf2qmoqBw2485o67edAuCmiTQq4GcmxhnP2banl77D79Zwly4416WWpWVifNA0WGONZ/s=" rel="noreferrer noopener" style="font-size:14px;text-decoration:underline;color:#6264a7;font-family:'Segoe UI','Helvetica Neue',Helvetica,Arial,sans-serif;" target="_blank" title="https://teams.microsoft.com/meetingoptions/?organizerid=97f10a8e-3843-4db7-8ef7-f449e82693d7&amp;tenantid=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;threadid=19_meeting_ytrlngq1ntytmzjkns00mmvjltg5otitytm1mtkyndkwnde2@thread.v2&amp;messageid=0&amp;language=en-us">Meeting options</a></div>

**Comment by abelbraaksma** [comment]
Missed it, it sadly. Like last time, it's there a recording made?

**Comment by vzarytovskii** [comment]
> Missed it, it sadly. Like last time, it's there a recording made?

Yeah, we are trying to figure out where to publish it, shouldn't take too much time.

**Comment by shazmodan** [comment]
I also missed it, is there a recording available yet?

**Comment by vzarytovskii** [comment]
> I also missed it, is there a recording available yet?

I'm preparing videos to be uploaded to FSSF YT channel.

**Comment by vzarytovskii** [comment]
Hey folks, we've just published both of our recordings for compiler community meetup. 
You can find them here: https://www.youtube.com/channel/UCsi00IVEgPoK7HvcpWDeSxQ/videos
If you'll find any issues (typos, or something in the video), please let me know.
