### ISSUE TITLE
F# Compiler Community Session - Tasks and Resumable State Machines - An Online Chat with Don and Vlad

### ISSUE THREAD

**Issue by vzarytovskii** [fsharp/fsfoundation#847]
Similar to the previous F# Compiler Community Sessions ([1](https://github.com/fsharp/fsfoundation/issues/845), [2](https://github.com/fsharp/fsfoundation/issues/846)) , on Wednesday 4 November 2020, 8pm GMT (UK time), 9pm CET (Central European Standard Time), 11pm MST (Moscow time), @dsyme and @vzarytovskii will be hosting a chat session together and with the community about the F# compiler.

**Update:** Recording can be found at [FSSF YouTube Channel](https://www.youtube.com/watch?v=GYi3ZMF8Pm0) 

**What**: Tasks and Resumable State Machines - An Online Chat with Don, Vlad and the community.

**When**: Wednesday 4 November 2020, 8pm GMT (UK time), 9pm CET (Central European Standard Time), 11pm MST (Moscow time),.

Topics for our third session:
- Task  builder to the F# standard library.
- Computation expressions, implemented via resumable code.
- Resumable code hosted in state machine objects recognized by the F# compiler.

Related PR: https://github.com/dotnet/fsharp/pull/6811

We will post a teams link here shortly before the call and record/archive the session. Please join us.

**Comment by MecuSorin** [comment]
A calendar [event](https://calendar.google.com/event?action=TEMPLATE&tmeid=NHQ0YWVnajE5dGFtM2o1MjYwZzBjYW1lbGwgbWVjdW1paGFpc29yaW5AbQ&tmsrc=mecumihaisorin%40gmail.com)

**Comment by vzarytovskii** [comment]
Hey everyone, session starts soon, you can join using this link: https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZWMyZWEzNTYtY2IwYy00YWFmLThiN2YtZGUxNjA1YTAxNTVm%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%7d

**Comment by realparadyne** [comment]
Will this be on the F# foundation YouTube channel soon?

**Comment by vzarytovskii** [comment]
> Will this be on the F# foundation YouTube channel soon?

@realparadyne Hey, sorry for the late reply, the video has been uploaded to FSSF channel.

**Comment by NatElkins** [comment]
Link here: https://www.youtube.com/watch?v=GYi3ZMF8Pm0
