### ISSUE TITLE
Enable HTTPS on foundation.fsharp.org

### ISSUE THREAD

**Issue by olivercoad** [fsharp/fsfoundation#848]
The links in the navbar should also be updated once https is enabled.

**Comment by ReedCopsey** [comment]
This can't happen currently (restrictions on underlying CMS), but will happen when the rewrite in process is completed. Thank you for bringing it up.

**Comment by olivercoad** [comment]
Hmm what kind of restrictions? NationBuilder has supported it [since 2018](https://nationbuilder.com/nationbuilder_sites_will_soon_be_upgraded_with_ssl_encryption).

Though if it's not an easy fix and there's already a rewrite in process to replace it soon then fair enough.

**Comment by ReedCopsey** [comment]
@olivercoad This should be done now. Thanks for pointing out that article. FYI - As of 2018, you couldn't do that for subdomains, but they do allow it now, and we managed to get it switched over.
