### ISSUE TITLE
F# Compiler Community Session - F# Parser Internals - An Online Chat with Don, Vlad and Community

### ISSUE THREAD

**Issue by vzarytovskii** [fsharp/fsfoundation#852]
Similar to the previous F# Compiler Community Sessions ([1](https://github.com/fsharp/fsfoundation/issues/845), [2](https://github.com/fsharp/fsfoundation/issues/846), [3](https://github.com/fsharp/fsfoundation/issues/847)) , on Tuesday 1st of December 2020, 7pm GMT (UK time), 8pm CET (Central European Standard Time), 10pm MST (Moscow time), 11am PT, @dsyme and @vzarytovskii will be hosting a chat session together and with the community about the F# parser.

What: F# Parser internals - An Online Chat with Don, Vlad and the community.

When: Tuesday 1st of December 2020, 7pm GMT (UK time), 8pm CET (Central European Standard Time), 10pm MST (Moscow time), 11am PT.

Topics for our fourth session:

F# Parser internals:
  - Parser, how does it work (covering fslex and fsyacc).
  - Error recovery.

Teams Link to join the session: https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDg3YjdlZjgtZmIxOC00YTNhLTg5NTYtYzI5ODA2OTk1ZWZk%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%7d

**Update**: recording is available on FSSF YT channel: https://youtu.be/3Zr0HNVcooU

**Comment by NatElkins** [comment]
Will the video be posted on https://www.youtube.com/channel/UCsi00IVEgPoK7HvcpWDeSxQ ?

**Comment by vzarytovskii** [comment]
> Will the video be posted on https://www.youtube.com/channel/UCsi00IVEgPoK7HvcpWDeSxQ ?

Hey, sorry for the late upload, the video is on the channel:

https://youtu.be/3Zr0HNVcooU
