### ISSUE TITLE
Broken link in "Serving Requests with IHttpHandler"

### ISSUE THREAD

**Issue by srid** [fsharp/fsfoundation#867]
The "summary" link in this section is broken.

https://fsharp.org/guides/web/#httphandler

![image](https://user-images.githubusercontent.com/3998/111337452-7d22c800-864c-11eb-80be-043537140736.png)

Incidentally, I was looking for the simplest project template for F# web app.

**Comment by srid** [comment]
By the way, I'm filing this issue here, only because this GitHub repo is linked to from the website's footer. Feel free to close if this is an inappropriate location!

**Comment by dsyme** [comment]
Thanks, closing, I removed this
