### ISSUE TITLE
Stale links

### ISSUE THREAD

**Issue by inputusernamehere** [fsharp/fsfoundation#881]
Hey, not sure if this is the right repo for this, but I found a couple of stale links on the website.

Under the Data Science section, the following links are stale:

This links to the wrong branch, but github automatically redirects so it's not a big issue:

- Try Online in Binder

The following links 404:

- Use Locally
- First steps with Accord.NET SVM in F#
- FSharp.Plotly
- Almost all the links under the `Tutorials and Introductions` section.
- Combining F# and Excel using Excel DNA
- Machine Learning with Excel: Combine the power of Excel, F# and R

CodePlex is shutting down so these links will be stale soon:

- NPOI
- EPPlus
- Plot functions from F# to Excel

Sidenote the link to Deedle is under the heading "Commercial packages", but I was not able to find any information about a commercial license. Maybe there is no longer a commercial version?

**Comment by dsyme** [comment]
Thanks I'll fix those now
