### ISSUE TITLE
Use F# on Linux instructions did not work

### ISSUE THREAD

**Issue by ScottHutchinson** [fsharp/fsfoundation#899]
https://github.com/fsharp/fsfoundation/blob/gh-pages/use/linux/index.md#option-1-install-the-cli-tools-and-use-your-own-editor

Following these instructions in WSL2 resulted in:

```
scott@xx:/mnt/c/Users/hutchinsons$ dotnet --info
dotnet: command not found
scott@xx:/mnt/c/Users/hutchinsons$ whereis dotnet
dotnet: /mnt/c/Program Files/dotnet/dotnet.exe /mnt/c/Program Files (x86)/dotnet/dotnet.exe
scott@xx:/mnt/c/Users/hutchinsons$ /mnt/c/Program Files/dotnet/dotnet --info
-bash: /mnt/c/Program: No such file or directory
scott@xx:/mnt/c/Users/hutchinsons$
```
@cartermp

**Comment by ScottHutchinson** [comment]
The ones the link points to.

**Comment by ShalokShalom** [comment]
Can this be reproduced/closed?

**Comment by ScottHutchinson** [comment]
I will look into this tomorrow.

**Comment by ScottHutchinson** [comment]
It looks like the script has changed, so I'm closing this issue.

**Comment by baronfel** [comment]
Worth noting these days that many repos have first class packages for the .Net SDK. e.g. for Ubuntu it's just 'apt install dotnet-sdk-7.0'. these instructions should probably take that into account.
