### ISSUE TITLE
F# Compiler Community Session - Debug improvements - An Online Chat with Don, Vlad and Community 

### ISSUE THREAD

**Issue by vzarytovskii** [fsharp/fsfoundation#910]
**UPDATE:** Teams meeting link: https://teams.microsoft.com/l/meetup-join/19%3ameeting_Mzc2NmFiYzQtYWY3Mi00ZjM2LWExMzgtNTRlMTYzYTNjOThi%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%7d

Hello everyone, this is an announcement for our 7th compiler community session.

**What:** F# Debug improvements - An Online Chat with Don, Vlad and the community.

**When:** Tuesday 1st of February2022, 11am PST (Pacific Time), 7pm GMT (UK time), 8pm CET (Central European Standard Time), 10pm MST (Moscow time), 11am PT ([check your local time here](https://everytimezone.com/s/9db1945c)).

**Topics for our seventh session:**

F# debug improvements.

**Previous sessions can be found here:** [1](https://github.com/fsharp/fsfoundation/issues/845), [2](https://github.com/fsharp/fsfoundation/issues/846), [3](https://github.com/fsharp/fsfoundation/issues/847), [4](https://github.com/fsharp/fsfoundation/issues/852) [5](https://github.com/fsharp/fsfoundation/issues/855), [6](https://github.com/fsharp/fsfoundation/issues/866) or on [F# Software Foundation YouTube channel](https://www.youtube.com/channel/UCsi00IVEgPoK7HvcpWDeSxQ)

**Link to the meeting will be posted 15m before the start**

**Comment by vzarytovskii** [comment]
**UPDATE**: Due to personal reasons, session was moved one week, to Tuesday, Feb 1st, 2022

**Comment by vzarytovskii** [comment]
UPDATE: Teams meeting link: https://teams.microsoft.com/l/meetup-join/19%3ameeting_Mzc2NmFiYzQtYWY3Mi00ZjM2LWExMzgtNTRlMTYzYTNjOThi%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%2297f10a8e-3843-4db7-8ef7-f449e82693d7%22%7d

**Comment by kerams** [comment]
This was recorded like always I hope :).
