### ISSUE TITLE
F# Community Dugnad Session with Kirk, Kathleen, and Don

### ISSUE THREAD

**Issue by KathleenDollard** [fsharp/fsfoundation#912]
We are restarting the Dugnad sessions for F#!  This is a chance of us to get together to "clean up the neighbourhood" of some core F# assets. the "Dugnad" concept inspired by @mathias-brandewinder. @tkshill, Kirk Shillingford offered to host.

Please join us! Teams link is below. This will be a social, fun occasion where we hang out - drinks and jokes and friendship are welcome but the aim is also to make some progress.

The invitation an open one. The aim will be to dive in and get stuff done rather than chat about what to do. Kirk Shilingford [@tkshill] will host.

Tuesday: 2022-02-08 noon Pacific / 8pm GMT

https://teams.microsoft.com/l/meetup-join/19%3ameeting_YjJkNGZkN2YtYjBlZS00MTcxLTgxNTQtMDcxZDVhNjc5MWU0%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%220e099197-7e30-40b4-b137-48962f86e452%22%7d

**Comment by davidglassborow** [comment]
When is the session Kathleen ?

**Comment by KathleenDollard** [comment]
Tues noon Pacific, 9PM GMT

Here are some things we can talk:

Kirk introduce/welcome
Victories since last Dugnad	
	Examples in .NET Core libraries
	Examples in FSharp.Core
	F# Language docs 
		F# Style Guide
	Learn F# Twitter is translated: Spanish, Portugese, English, Polish (new effort) - Angel Munoz and Ad...
	Luis's videos (other learn)

Web presence
	Test, use, simplify and clean https://fsharp.org/ (souce https://github.com/fsharp/fsfoundation/)
	Help community improve https://en.wikipedia.org/wiki/F_Sharp_(programming_language)
	Help orient more traffic to the high quality https://dotnet.microsoft.com/languages/fsharp
	Check google searches for "F#" 
	Discuss multi-language aspects, e.g. Russian/German/Chinese/Korean F# Wikipedia pages

Technical docs
	FSharp.Core docs at https://fsharp.github.io/fsharp-core-docs/
	Work on FSharp.Formatting (fsdocs, used to build docs)
		*Such as separate page/member (issues in repo)

Learn
	StackOverflow review (at least get a new date that something is still relevant
	Improve https://fsharp.org/learn/
	Check google searches for "Learn F#" and "F# Tutorial"

Language design process
	Spring clean https://github.com/fsharp/fslang-design/ and https://github.com/fsharp/fslang-suggestions

Simple F# initiative
	Addressing bad compiler messages	
		Finding and finding ways we get those messages and new wording

Community libraries/community tooling
	Spring clean in https://fsharp.github.io/FSharp.Data/
	Ionide
	Fable
	...

**Comment by ThisFunctionalTom** [comment]
@KathleenDollard I guess the first time you posted had the correct time in GMT.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/3315570/152932315-b5828569-ba39-48ca-be0c-2e34250e1a7b.png">

**Comment by dsyme** [comment]
Yup, 8pm GMT. See you there!

**Comment by daniellittledev** [comment]
Documentation for applicative computation expressions has not yet been added to the [official documentation for CEs](https://docs.microsoft.com/dotnet/fsharp/language-reference/computation-expressions).

https://devblogs.microsoft.com/dotnet/announcing-f-5-preview-1/#comments

**Comment by cartermp** [comment]
@daniellittledev would you like to contribute? I'll happily review

**Comment by baronfel** [comment]
@daniellittledev wrote an issue for tracking this gap here: https://github.com/dotnet/docs/issues/28134

**Comment by dsyme** [comment]
All the docs for computation expressions could do with a complete revamp I think

Among other things, we need to show the recipies for people ("I want a DSL supporting yield and for and let and custom operators") much like F# for Fun and Profit does.

Some relevant notes on applicatives are here https://github.com/dsyme/fsharp-presentations/blob/master/design-notes/rethinking-applicatives.md

**Comment by dsyme** [comment]
For next time, to track

* [ ] F# for Python devs
* [ ] F# for Node devs
* [ ] F# for JavaScript/Typescript devs
* [ ] F# for Elm devs
* [ ] F# for Scala devs
* [ ] F# for Haskell devs
* [ ] F# for OCaml devs

**Comment by daniellittledev** [comment]
@cartermp @baronfel thanks, I haven't had a lot of time recently (newborns take up a lot) and would be happy to try, but I wouldn't want to delay it if someone else can pick it up.

**Comment by dsyme** [comment]
I'd like to add a new top level section for the topics covered by the dugnad called "Social Proof" - covering https://fsharp.org/testimonials in particular, but also social proof on https://docs.microsoft.com/ or https://dotnet.microsoft.com/, also the "F# Bonanza" video.

We have lots of good social proof in the F# community and the testimonials are pretty good, but we could for example have a regular twitter bot to tweet a snippet quote and one testimonial each week.  A drip-drip of social proof is really effective.

**Comment by MecuSorin** [comment]
It was recorded? Can you provide a link, please, if available. Thanks!

**Comment by vzarytovskii** [comment]
> It was recorded? Can you provide a link, please, if available. Thanks!

It was recorded, yes, however, not yet uploaded as far as I know. @KathleenDollard may have more information on that.

**Comment by sashang** [comment]
> It was recorded? Can you provide a link, please, if available. Thanks!

https://www.youtube.com/watch?v=ylgxQkrZG1c

**Comment by sashang** [comment]
> For next time, to track
> 
> * [ ]  F# for Python devs
> * [ ]  F# for Node devs
> * [ ]  F# for JavaScript/Typescript devs
> * [ ]  F# for Elm devs
> * [ ]  F# for Scala devs
> * [ ]  F# for Haskell devs
> * [ ]  F# for OCaml devs

Adding 
* [ ] F# for C/C++ devs
