### ISSUE TITLE
F# Compiler Community Session - Extending string interpolation syntax - Community Feature Review

### ISSUE THREAD

**Issue by abonie** [fsharp/fsfoundation#932]
Hello everyone, this is an announcement of another F# compiler community session

**What:** Community Feature Review for RFC FS-1132: Interpolated strings syntax with multiple dollar signs

I will go through the [RFC FS-1132](https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1132-better-interpolated-triple-quoted-strings.md) of this upcoming feature and demonstrate how it will work in practice.

**When:** Tuesday 28th of March, 8:00pm CEST (Central European Summer Time, UTC+2), 11:00am PDT (Pacific Daylight Time)

**Other community sessions can be found here:** [fsharp/fsfoundation](https://github.com/fsharp/fsfoundation/issues?q=is%3Aissue+%22F%23+Compiler+Community+Session%22) or on [F# Foundation Youtube channel](https://www.youtube.com/channel/UCsi00IVEgPoK7HvcpWDeSxQ)

**Link to the meeting will be posted 15m before the start**

edit: [link to the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDA5NzI5MTQtMzI4My00MGUzLWIyMjEtMDBjYjY0ZWRlZDRl%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%222d662b27-c8c2-4014-8481-591a28889343%22%7d)

**Comment by abonie** [comment]
Just an update - will have to reschedule from the original planned date (today) to sometime next week, will update the OP soon with a new date

**Comment by baronfel** [comment]
Here's a link to an event set at the time in the OP, so folks can easily see the time in their time zone: [Event time in your local time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=+F%2523+Compiler+Community+Session+-+Extending+string+interpolation+syntax+-+Community+Feature+Review&iso=20230328T20)

**Comment by vzarytovskii** [comment]
> Here's a link to an event set at the time in the OP, so folks can easily see the time in their time zone: [Event time in your local time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=+F%2523+Compiler+Community+Session+-+Extending+string+interpolation+syntax+-+Community+Feature+Review&iso=20230328T20)

I think you have 8pm UTC, but it should be 8pm CEST (or Prague time)

**Comment by baronfel** [comment]
check now @vzarytovskii?

**Comment by abonie** [comment]
Here's a link to join the meeting: https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDA5NzI5MTQtMzI4My00MGUzLWIyMjEtMDBjYjY0ZWRlZDRl%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%222d662b27-c8c2-4014-8481-591a28889343%22%7d

**Comment by abelbraaksma** [comment]
Note that the RFC has since moved:

* https://github.com/fsharp/fslang-design/blob/main/FSharp-8.0/FS-1132-better-interpolated-triple-quoted-strings.md
